title: AltaMira Collaboratory
description: A collective of researchers working at the intersection of generative AI, the sciences, and engineering.
theme: jekyll-now
show_downloads: false
google_analytics: # Add your Google Analytics ID here if needed

# Navigation
nav:
  - title: Home
    url: /
  - title: Members
    url: /members/
  - title: Publications
    url: /publications/